agent:
  _target_: agents.drm.DrQV2Agent
  # _target_: agents.drqv2.DrQV2Agent
  # drm settings
  dr_tau : 0.025
  use_perturbation: true
  perturbation_interval: 5000
  perturbation_rate: 2
  max_perturbation: 0.9
  min_perturbation: 0.2
  use_drg_exploration: true
  beta_threshold: 0.2
  exploration_temperature: 0.1
  use_drg_exploitation: true
  exploitation_temperature: 0.02
  exploitation_expectile: 0.9
  max_exploitation_lambda: 0.6
  # basic settings
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  critic_target_tau: 0.01
  update_every_steps: 2
  use_tb: ${use_tb}
  num_expl_steps: 2000
  hidden_dim: 1024
  feature_dim: ${feature_dim}
  stddev_schedule: ${stddev_schedule}
  stddev_clip: 0.3
